# Generated by Django 5.2.6 on 2025-09-21 10:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo Contratto')),
                ('file', models.FileField(upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='File Contratto')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract_type', models.CharField(blank=True, choices=[('purchase', 'Contratto di Compravendita'), ('service', 'Contratto di Servizio'), ('employment', 'Contratto di Lavoro'), ('rental', 'Contratto di Locazione'), ('nda', 'Accordo di Riservatezza'), ('partnership', 'Contratto di Partnership'), ('license', 'Contratto di Licenza'), ('other', 'Altro')], max_length=20, verbose_name='Tipo Contratto')),
                ('parties', models.TextField(blank=True, verbose_name='Parti Coinvolte')),
                ('duration', models.CharField(blank=True, max_length=500, verbose_name='Durata')),
                ('key_obligations', models.TextField(blank=True, verbose_name='Obblighi Principali')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Basso'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=10, verbose_name='Livello di Rischio')),
                ('extracted_text', models.TextField(blank=True)),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Analisi AI')),
                ('analyzed', models.BooleanField(default=False)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contratto',
                'verbose_name_plural': 'Contratti',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrizione Scadenza')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data Scadenza')),
                ('days_notice', models.IntegerField(blank=True, null=True, verbose_name='Giorni di Preavviso')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='analyzer.contract')),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RiskClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_text', models.TextField(verbose_name='Testo della Clausola')),
                ('risk_description', models.TextField(verbose_name='Descrizione del Rischio')),
                ('severity', models.CharField(choices=[('low', 'Basso'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=10, verbose_name='Gravità')),
                ('recommendation', models.TextField(verbose_name='Raccomandazione')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_clauses', to='analyzer.contract')),
            ],
            options={
                'verbose_name': 'Clausola Rischiosa',
                'verbose_name_plural': 'Clausole Rischiose',
            },
        ),
    ]
